# Generated by Django 5.0.3 on 2025-03-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_journalentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='title',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(),
        ),
    ]
